/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JScrollPane;

import controller.DatabaseController;
import model.DatabaseConnection;

/**
 *
 * @author fatih
 */
public class DatabaseTablePanel extends javax.swing.JPanel {
    private String[] table;
    private JScrollPane jScrollPane;
    /**
     * Creates new form DatabaseTable
     */
    public DatabaseTablePanel(JScrollPane jScrollPane) {
        initComponents();
        setTable();
        this.jScrollPane = jScrollPane;
        tableComboBox.setModel(new DefaultComboBoxModel<>(table));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tableComboBox = new javax.swing.JComboBox<>();
        bukaButton = new javax.swing.JButton();

        judulLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        judulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLabel.setText("Selamat Datang");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Silakan pilih tabel yang ingin dilihat:");

        bukaButton.setText("BUKA");
        bukaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(tableComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bukaButton)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bukaButton))
                .addContainerGap(279, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setTable(){
        String path = System.getProperty("user.dir") + "\\src\\model\\database\\data_user" + MainFrame.user_id  + ".db";
        DatabaseController dc = new DatabaseController();

        this.table = dc.getTable(path).toArray(new String[0]);
    }
    private void bukaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukaButtonActionPerformed
        String path = System.getProperty("user.dir") + "\\src\\model\\database\\data_user" + MainFrame.user_id  + ".db";
        DatabaseController dc = new DatabaseController();
        String[] headers = dc.getColumnName((String)tableComboBox.getSelectedItem(), path);
        List<String[]> values = dc.getData((String) tableComboBox.getSelectedItem(), path);
        TableFrame tFrame = new TableFrame(headers, values);
        tFrame.setVisible(true);
    }//GEN-LAST:event_bukaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bukaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JComboBox<String> tableComboBox;
    // End of variables declaration//GEN-END:variables
}
