/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import controller.DatabaseController;

/**
 *
 * @author fatih
 */
public class DatabaseTablePanel extends javax.swing.JPanel {
    private String[] table;
    private JScrollPane jScrollPane;
    private DatabaseController dc;
    /**
     * Creates new form DatabaseTable
     */
    public DatabaseTablePanel(JScrollPane jScrollPane) {
        initComponents();
        dc = new DatabaseController();
        setTable();
        this.jScrollPane = jScrollPane;
        tableComboBox.setModel(new DefaultComboBoxModel<>(table));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tableComboBox = new javax.swing.JComboBox<>();
        bukaButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();

        judulLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        judulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLabel.setText("Selamat Datang");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Silakan pilih tabel yang ingin dilihat:");

        bukaButton.setText("BUKA");
        bukaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukaButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(255, 0, 51));
        hapusButton.setText("HAPUS");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hapusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bukaButton))
                    .addComponent(tableComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bukaButton)
                    .addComponent(hapusButton))
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setTable(){
        String path = System.getProperty("user.dir") + "\\src\\model\\database\\data_user" + MainFrame.userId  + ".db";

        this.table = dc.getTable(path).toArray(new String[0]);
    }
    
    private void bukaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukaButtonActionPerformed
        String path = System.getProperty("user.dir") + "\\src\\model\\database\\data_user" + MainFrame.userId  + ".db";
        String[] headers = dc.getColumnName((String)tableComboBox.getSelectedItem(), path);
        List<String[]> values = dc.getData((String) tableComboBox.getSelectedItem(), path);
        TableFrame tFrame = new TableFrame(headers, values);
        tFrame.setVisible(true);
    }//GEN-LAST:event_bukaButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Apakah anda ingin menghapus tabel " + (String)tableComboBox.getSelectedItem());
        
        if(choice == JOptionPane.YES_OPTION){
            if(dc.deleteTable(MainFrame.userId, (String)tableComboBox.getSelectedItem())){
                setTable();
                tableComboBox.setModel(new DefaultComboBoxModel<>(table));
                JOptionPane.showMessageDialog(this, "Berhasil menghapus tabel!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Gagal menghapus tabel!");
            }
        }
    }//GEN-LAST:event_hapusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bukaButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JComboBox<String> tableComboBox;
    // End of variables declaration//GEN-END:variables
}
